version: "3.5"

services:
  pocketbase:
    container_name: pocketbase
    build:
      context: ./pocketbase
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    volumes:
      - pocketbase_data:/pb/pb_data
      - ./pocketbase/pb_hooks:/pb/pb_hooks
      - ./pocketbase/pb_data:/pb/pb_data
      - ./pocketbase/pb_migrations:/pb/pb_migrations
    networks:
      - my-network

  sveltekit:
    container_name: sveltekit
    build:
      context: ./sveltekit
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./sveltekit:/app
      - /app/node_modules
    networks:
      - my-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.dev.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - sveltekit
      - pocketbase
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  pocketbase_data:
