# Step 1: Use an official Node.js image as the base image
FROM node:22 AS builder

# Install Bun
RUN npm install -g bun

# Set the working directory in the container
WORKDIR /app

# Copy package.json and bun.lockb files
COPY package.json bun.lockb ./

# Install project dependencies using Bun
RUN npx bun install

# Copy the rest of the application source code
COPY . .

# Expose the port the application will run on
EXPOSE 8080
