# Step 1: Build the application
FROM oven/bun AS builder

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json files
COPY package.json bun.lockb ./

# Run your build process
RUN bun install

COPY . .

# Expose the port the application will run on
EXPOSE 8080

#Start the BUN server
CMD ["bun", "run", "dev", "--host"]
